// Configuration for the four sector Google Sheets.
// Column keys map to internal keys; values are the exact header text from each sheet.

export const APP_CONFIG = {
  loginPassword: "yost-ice-2025",

  refreshIntervalMs: 5 * 60 * 1000, // 5 minutes

  // Fetch Google Apps Script URLs directly from the browser.
  // If you ever hit CORS issues, you can optionally set this to a proxy URL
  // (e.g. "https://corsproxy.io/?") and the app will route requests through it.
  corsProxy: "/api/proxy?url=",

  forms: [
    {
      id: "ice-quality-reports",
      label: "Ice Quality Reports",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1uvyEJpFY8eGcuc6Gz22sZn6pnVxsZ1gElv8YMnzsSM4/edit?gid=753097146#gid=753097146",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbzRXXdFNiavQCbLG0mDiIAGdhksFA5cXt209rAc9hcYVovVmE9v5ph98idIplc9RVhObQ/exec",
      columns: {
        timestamp: "Timestamp",
        date: "Date",
        name: "Name",
        humidity: "Humidity",
        airTemperature: "Air Temperature",
        surfaceTemperature: "Surface Temperature",
        waterTemp: "Water Temp",
        setPoint: "Set Point",
        slabTemperature: "Slab Temperature",
        supplyTemperature: "Supply Temperature",
        returnTemperature: "Return Temperature",
        notes: "Notes",
        time: "Time",
        outsideAirTemp: "Outside Air Temp",
        outsideRelHumidity: "Outside Relative Humidity",
        avgIceSurfaceTemp: "Avg Ice Surface Temp",
        avgHumidity: "Avg Humidity",
        avgAirTemp: "Avg Air Temp",
        diffSlabSurface: "Diff slab and surface temp",
        dewPoint: "Dew Point (ideal is 35-40)",
        avgDewPointMonth: "AVG Dew Point per Month",
      },
      kpis: [
        { id: "last-check", label: "Last check", columnKey: "timestamp", format: "timestamp" },
        { id: "surface-temp", label: "Surface temp", columnKey: "surfaceTemperature", format: "number" },
        { id: "humidity", label: "Humidity", columnKey: "humidity", format: "number" },
        { id: "notes", label: "Notes", columnKey: "notes", format: "string" },
      ],
    },
    {
      id: "softball-therapy-pool",
      label: "Softball Therapy Pool Checks",
      sheetUrl: "https://docs.google.com/spreadsheets/d/10XBiTfF0QTCC3znxr2nCdLM4nn0j29phQfbdmHbFeOA/edit?gid=97978185#gid=97978185",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbzjcYYOX3UPAQqLIBysV9DKzmM7p-_JjLeoVAjxN4YG1wAYn5w7NKePP_9tlyT7xSlL/exec",
      columns: {
        timestamp: "Timestamp",
        date: "DATE",
        time: "TIME",
        name: "Name",
        chlorineHot: "Chlorine (Hot Tub)",
        chlorineCold: "Chlorine (Cold Tub)",
        pHHot: "pH (Hot Tub)",
        pHCold: "pH (Cold Tub)",
        alkalinityHot: "Alkalinity (Hot Tub)",
        alkalinityCold: "Alkalinity (Cold Tub)",
        calciumHot: "Calcium Hardness (Hot Tub)",
        calciumCold: "Calcium Hardness (Cold Tub)",
        tempHot: "Temperature (Hot Tub)",
        tempCold: "Temperature (Cold Tub)",
        orpHot: "ORP (mV) (Hot Tub)",
        orpCold: "ORP (mV) (Cold Tub)",
        tdsHot: "TDS Level (Hot Tub)",
        tdsCold: "TDS Level (Cold Tub)",
        readings: "Readings",
        shock: "Shock? ",
        drainClean: "Drain/Clean?",
        comments: "Comments",
      },
      kpis: [
        { id: "last-check", label: "Last check", columnKey: "timestamp", format: "timestamp" },
        { id: "chlorine-hot", label: "Hot Tub", columnKey: "chlorineHot", format: "number" },
        { id: "chlorine-cold", label: "Cold Tub", columnKey: "chlorineCold", format: "number" },
        { id: "comments", label: "Comments", columnKey: "comments", format: "string" },
      ],
    },
    {
      id: "fisher-therapy-pool",
      label: "Fisher Therapy Pool Checks",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1pdQTH-sbl41UA_yWMEWTyoGiruAqLVL61ym4ikHZ1Qk/edit?gid=462989413#gid=462989413",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbx7HJMz6_Qs3OmCAB1WSqs1bSEyUyRjcrNE1auGZ4ejioWoGLiS0JWW98LL3XE7my1V/exec",
      columns: {
        timestamp: "Timestamp",
        date: "Date",
        time: "Time",
        name: "Name",
        bromine: "Bromine",
        pH: "pH",
        alkalinity: "Alkalinity",
        calciumHardness: "Calcium Hardness",
        temperature: "Temperature",
        orp: "ORP (mV)",
        tds: "TDS Level",
        readings: "Readings",
        shock: "Shock? ",
        drainClean: "Drain/Clean?",
        comments: "Comments",
      },
      kpis: [
        { id: "last-check", label: "Last check", columnKey: "timestamp", format: "timestamp" },
        { id: "bromine", label: "Bromine", columnKey: "bromine", format: "number" },
        { id: "temperature", label: "Temperature", columnKey: "temperature", format: "number" },
        { id: "comments", label: "Comments", columnKey: "comments", format: "string" },
      ],
    },
    {
      id: "yost-ice-depth",
      label: "Yost Ice Depth Checks",
      sheetUrl: "https://docs.google.com/spreadsheets/d/15IEsNUxi_YsNDZMTRy3Pjqz7znd8QX9G5tO1fuj82wA/edit?gid=1000276266#gid=1000276266",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbxpm5FWhB1F9zG1Upkc8rT2LMHrsfebqzuk7h56NHMd1doHiCqlEqJld6v3RiYGE4G4/exec",
      columns: {
        timestamp: "Timestamp",
        date: "",
        name: "Name",
        threshold: "1 (Threshold)",
        southGoal: "2 (South Goal)",
        seCorner: "3 (SE Corner)",
        seFaceoff: "4 (SE Faceoff Dot)",
        swFaceoff: "5 (SW Faceoff Dot)",
        southBluePenalty: "6 (South Blue Line Penalty Box)",
        southBlueMiddle: "7 (South Blue Line Middle)",
        southBlueBench: "8 (South Blue Line Bench)",
        redLineBenches: "9 (Red Line Team Benches)",
        centerIce: "10 (Center Ice)",
        redLineScorer: "11 (Red Line Scorer's Bench)",
        northBluePenalty: "12 (North Blue Line Penalty Box)",
        northBlueMiddle: "13 (North Blue Line Middle)",
        northBlueBench: "14 (North Blue Line Bench)",
        neFaceoff: "15 (NE Faceoff Dot)",
        nwFaceoff: "16 (NW Faceoff Dot)",
        nwCorner: "17 (NW Corner)",
        northGoal: "18 (North Goal)",
        neCorner: "19 (NE Corner)",
        avg: "AVG",
        avgWithoutCorners: "AVG (w/o corners)",
      },
      kpis: [
        { id: "last-check", label: "Last check", columnKey: "timestamp", format: "timestamp" },
        { id: "name", label: "Checked by", columnKey: "name", format: "string" },
        { id: "avg", label: "Avg depth", columnKey: "avg", format: "number" },
        { id: "center", label: "Center ice", columnKey: "centerIce", format: "number" },
      ],
    },
  ],
};
