// Configuration for the four sector Google Sheets.
// Column keys map to internal keys; values are the exact header text from each sheet.

export const APP_CONFIG = {
  loginPassword: "yost-ice-2025",

  refreshIntervalMs: 5 * 60 * 1000, // 5 minutes

  // Fetch Google Apps Script URLs directly from the browser.
  // If you ever hit CORS issues, you can optionally set this to a proxy URL
  // (e.g. "https://corsproxy.io/?") and the app will route requests through it.
  corsProxy: "/api/proxy?url=",

  forms: [
    {
      id: "ice-quality-reports",
      label: "Ice Quality Reports",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1uvyEJpFY8eGcuc6Gz22sZn6pnVxsZ1gElv8YMnzsSM4/edit?gid=753097146#gid=753097146",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbzRXXdFNiavQCbLG0mDiIAGdhksFA5cXt209rAc9hcYVovVmE9v5ph98idIplc9RVhObQ/exec",
      columns: {
        timestamp: "Timestamp",
        date: "Date",
        name: "Name",
        humidity: "Humidity",
        airTemperature: "Air Temperature",
        surfaceTemperature: "Surface Temperature",
        waterTemp: "Water Temp",
        setPoint: "Set Point",
        slabTemperature: "Slab Temperature",
        supplyTemperature: "Supply Temperature",
        returnTemperature: "Return Temperature",
        notes: "Notes",
        time: "Time",
        outsideAirTemp: "Outside Air Temp",
        outsideRelHumidity: "Outside Relative Humidity",
        avgIceSurfaceTemp: "Avg Ice Surface Temp",
        avgHumidity: "Avg Humidity",
        avgAirTemp: "Avg Air Temp",
        diffSlabSurface: "Diff slab and surface temp",
        dewPoint: "Dew Point (ideal is 35-40)",
        avgDewPointMonth: "AVG Dew Point per Month",
      },
      kpis: [
        { id: "ag", label: "Avg Ice Surface Temp", columnKey: "avgIceSurfaceTemp", format: "number" },
        { id: "ah", label: "Avg Humidity", columnKey: "avgHumidity", format: "number" },
        { id: "ai", label: "Avg Air Temp", columnKey: "avgAirTemp", format: "number" },
        { id: "ak", label: "Avg Dew Point / Month", columnKey: "avgDewPointMonth", format: "number" },
      ],
      manualRows: [
        {
          timestamp: "2026-04-06T08:15:00-04:00",
          date: "2026-04-06",
          time: "08:15 AM",
          name: "Facilities Staff",
          humidity: 44,
          surfaceTemperature: 23.4,
          notes: "Local fallback sample entry",
        },
      ],
    },
    {
      id: "softball-tub-check",
      label: "Softball Tub Check",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1BlBtDMQzfhuRSFXsggr6nTbdHh8u9xT6bc23QMoSQyQ/edit?gid=108977191#gid=108977191",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbwyzTEfHD2CKrqSQHcunAZNcUuIZI8kK3IFsDCgDZ8_1b1MFE6XtZ6vYZiek8o1SZfE/exec?sheet=Softball",
      columns: {
        timestamp: "Submission Date",
        building: "Select building:",
        selectTub: "Select tub",
        dropsReader: "Drops/Reader",
        pH: "pH",
        chlorine: ["Chlorine", "Bromine"],
        alkalinity: "Alkalinity",
        poolTemperature: "Pool Temperature",
        cl: "CL",
        clPpm: "CL (ppm)",
        orp: "ORP",
        whatChemicals: "What chemicals were added?",
        tubCheck: "Tub Check",
      },
      kpis: [
        { id: "a", label: "Last Submission", columnKey: "timestamp", format: "date" },
        { id: "c", label: "Tub", columnKey: "selectTub", format: "string" },
        { id: "e-hot", label: "pH (Hot)", columnKey: "pH", format: "number", filterBy: { columnKey: "selectTub", value: "Hot" } },
        { id: "e-cold", label: "pH (Cold)", columnKey: "pH", format: "number", filterBy: { columnKey: "selectTub", value: "Cold" } },
        { id: "f-hot", label: "Chlorine (Hot)", columnKey: "chlorine", format: "number", filterBy: { columnKey: "selectTub", value: "Hot" } },
        { id: "f-cold", label: "Chlorine (Cold)", columnKey: "chlorine", format: "number", filterBy: { columnKey: "selectTub", value: "Cold" } },
        { id: "h-hot", label: "Pool Temp (Hot)", columnKey: "poolTemperature", format: "number", filterBy: { columnKey: "selectTub", value: "Hot" } },
        { id: "h-cold", label: "Pool Temp (Cold)", columnKey: "poolTemperature", format: "number", filterBy: { columnKey: "selectTub", value: "Cold" } },
        { id: "l", label: "What Chemicals", columnKey: "whatChemicals", format: "string" },
      ],
    },
    {
      id: "fisher-therapy-pool",
      label: "Fisher Therapy Pool Checks",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1BlBtDMQzfhuRSFXsggr6nTbdHh8u9xT6bc23QMoSQyQ/edit?gid=434939189#gid=434939189",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbwyzTEfHD2CKrqSQHcunAZNcUuIZI8kK3IFsDCgDZ8_1b1MFE6XtZ6vYZiek8o1SZfE/exec?sheet=Baseball",
      columns: {
        timestamp: "Submission Date",
        building: "Select building:",
        selectTub: "Baseball tub",
        dropsReader: "Drops/Reader",
        pH: "pH",
        chlorine: ["Chlorine", "Bromine"],
        alkalinity: "Alkalinity",
        poolTemperature: "Pool Temperature",
        cl: "CL",
        clPpm: "CL (ppm)",
        calHard: "Cal Hard",
        whatChemicals: "What chemicals were added?",
        tubCheck: "Tub Check",
      },
      kpis: [
        { id: "a", label: "Last Submission", columnKey: "timestamp", format: "date" },
        { id: "c", label: "Tub", columnKey: "selectTub", format: "string" },
        { id: "e", label: "pH", columnKey: "pH", format: "number" },
        { id: "f", label: "Chlorine", columnKey: "chlorine", format: "number" },
        { id: "h", label: "Pool Temp", columnKey: "poolTemperature", format: "number" },
        { id: "l", label: "What Chemicals", columnKey: "whatChemicals", format: "string" },
      ],
    },
    {
      id: "yost-ice-depth",
      label: "Yost Ice Depth Checks",
      sheetUrl: "https://docs.google.com/spreadsheets/d/15IEsNUxi_YsNDZMTRy3Pjqz7znd8QX9G5tO1fuj82wA/edit?gid=1000276266#gid=1000276266",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbxpm5FWhB1F9zG1Upkc8rT2LMHrsfebqzuk7h56NHMd1doHiCqlEqJld6v3RiYGE4G4/exec",
      columns: {
        timestamp: "Timestamp",
        date: "",
        name: "Name",
        threshold: "1 (Threshold)",
        southGoal: "2 (South Goal)",
        seCorner: "3 (SE Corner)",
        seFaceoff: "4 (SE Faceoff Dot)",
        swFaceoff: "5 (SW Faceoff Dot)",
        southBluePenalty: "6 (South Blue Line Penalty Box)",
        southBlueMiddle: "7 (South Blue Line Middle)",
        southBlueBench: "8 (South Blue Line Bench)",
        redLineBenches: "9 (Red Line Team Benches)",
        centerIce: "10 (Center Ice)",
        redLineScorer: "11 (Red Line Scorer's Bench)",
        northBluePenalty: "12 (North Blue Line Penalty Box)",
        northBlueMiddle: "13 (North Blue Line Middle)",
        northBlueBench: "14 (North Blue Line Bench)",
        neFaceoff: "15 (NE Faceoff Dot)",
        nwFaceoff: "16 (NW Faceoff Dot)",
        nwCorner: "17 (NW Corner)",
        northGoal: "18 (North Goal)",
        neCorner: "19 (NE Corner)",
        avg: "AVG",
        avgWithoutCorners: "AVG (w/o corners)",
      },
      kpis: [
        { id: "a", label: "Implementation Date", columnKey: "timestamp", format: "date" },
        { id: "w", label: "AVG", columnKey: "avg", format: "number" },
        { id: "x", label: "AVG w/o corners", columnKey: "avgWithoutCorners", format: "number" },
      ],
      manualRows: [
        {
          timestamp: "2026-04-06T10:00:00-04:00",
          name: "Facilities Staff",
          avg: 1.15,
          centerIce: 1.12,
          threshold: 1.1,
          northGoal: 1.18,
          southGoal: 1.14,
        },
      ],
    },
    {
      id: "fisher-stadium-astroturf",
      label: "Fisher Stadium AstroTurf",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1OOq7jbepuW1lRzCpIMoyHxHem3SY00oFhktF83u6DCM/edit?gid=1170812430#gid=1170812430",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbwp_dytjb3CMCEGbcWv7Ekg7vDqwkWiuDRaUy4UzPdsUeDE0ARwuF-IlvDGaSZ8Xd3v/exec",
      columns: {
        timestamp: "Date",
        date: "Date",
        avgClegg: "Avg Clegg",
        properInfillDepth: "Proper Infill Depth (Y/N)",
        infillLocation1: "Infill Added Location 1",
        infillLocation2: "INFILL added location 2",
        groomDirection: "Groom (Brush/ Rake) Direction (W or E)",
        sweep: "Sweep",
        magnet: "Magnet",
        snowRemoval: "Snow Removal",
        annualAerating: "Annual Aerating & Cleaning (Turfix)",
        additionalActivities: "Additional Maint Activities & Notes",
      },
      kpis: [
        { id: "d", label: "Infill Added Location 1", columnKey: "infillLocation1", format: "string" },
        { id: "e", label: "Infill Added Location 2", columnKey: "infillLocation2", format: "string" },
        { id: "f", label: "Groom Direction", columnKey: "groomDirection", format: "string" },
        { id: "g", label: "Sweep", columnKey: "sweep", format: "string" },
        { id: "h", label: "Magnet", columnKey: "magnet", format: "string" },
        { id: "i", label: "Snow Removal", columnKey: "snowRemoval", format: "string" },
        { id: "k", label: "Additional Maint Activities", columnKey: "additionalActivities", format: "string" },
      ],
      latestRowOnlyForKpis: true,
    },
    {
      id: "alumni-field-astroturf",
      label: "Alumni Field AstroTurf",
      sheetUrl: "https://docs.google.com/spreadsheets/d/1djYCiA90FylgzsHsvkzYYU5E75WDa66offbmpZvWF38/edit?gid=1170812430#gid=1170812430",
      sheetJsonUrl:
        "https://script.google.com/macros/s/AKfycbwowO5EgWsTcaMYByKAbROWJluwAeQ1NH0LB4G4FiI_HLbrgzoBQh-P8tfPpuMHNxD0WQ/exec",
      columns: {
        timestamp: "Date",
        date: "Date",
        avgClegg: "Avg Clegg",
        properInfillDepth: "Proper Infill Depth (Y/N)",
        infillLocation1: "Infill Location 1",
        infillLocation2: "Infill Location 2",
        infillLocation3: "Infill Location 3",
        infillLocation4: "Infill Location 4",
        infillLocation5: "Infill Location 5",
        turfInspection: "turf inspection",
        groomDirection: "Groom (Brush/ Rake) Direction (W or E)",
        sweep: "Sweep",
        magnet: "Magnet",
        snowRemoval: "Snow Removal",
        annualAerating: "Annual Aerating & Cleaning (Turfix)",
        additionalActivities: "Additional Maint Activities & Notes",
      },
      kpis: [
        { id: "d", label: "Infill Location 1", columnKey: "infillLocation1", format: "string" },
        { id: "e", label: "Infill Location 2", columnKey: "infillLocation2", format: "string" },
        { id: "j", label: "Groom Direction", columnKey: "groomDirection", format: "string" },
        { id: "k", label: "Sweep", columnKey: "sweep", format: "string" },
        { id: "l", label: "Magnet", columnKey: "magnet", format: "string" },
        { id: "m", label: "Snow Removal", columnKey: "snowRemoval", format: "string" },
        { id: "o", label: "Additional Maint Activities", columnKey: "additionalActivities", format: "string" },
      ],
      latestRowOnlyForKpis: true,
    },
  ],
};
